[env:waveshare_s3_5b]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
board_build.memory_type = qio_opi
board_build.psram_type = opi
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DLV_CONF_INCLUDE_SIMPLE
    -std=gnu++17
    -Iinclude
    -Iconf
    -I../ui

build_unflags =
    -std=gnu++11
    -std=gnu++14

build_src_filter =
    +<*>

lib_deps =
    lvgl/lvgl@^9.5.0
    git+ssh://git@github.com/esp-arduino-libs/ESP32_Display_Panel.git#v1.0.4
    git+ssh://git@github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.3
    git+ssh://git@github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.1

monitor_speed = 1000000
monitor_filters = esp32_exception_decoder
