[env:waveshare_s3_5b]
platform = git+ssh://git@github.com/platformio/platform-espressif32.git
platform_packages =
    framework-arduinoespressif32 @ git+ssh://git@github.com/espressif/arduino-esp32.git#3.0.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DLV_CONF_INCLUDE_SIMPLE
    -std=gnu++17
    -DLCD_RGB_ELEMENT_ORDER_RGB=0
    -DLCD_RGB_ELEMENT_ORDER_BGR=1
    -Iinclude
    -Iconf
    -I../ui

build_unflags =
    -std=gnu++11
    -std=gnu++14

build_src_filter =
    +<*>
    +<../../ui/*.c>

lib_deps =
    lvgl/lvgl@^9.5.0
    git+ssh://git@github.com/esp-arduino-libs/ESP32_Display_Panel.git#v1.0.4
    git+ssh://git@github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.3
    git+ssh://git@github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.1

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
