// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui_redo

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_Panel1 = NULL;
lv_obj_t *ui_Container1 = NULL;
lv_obj_t *ui_Container4 = NULL;
lv_obj_t *ui_Label1 = NULL;
lv_obj_t *ui_Label2 = NULL;
lv_obj_t *ui_Container2 = NULL;
lv_obj_t *ui_Chart1 = NULL;
lv_obj_t *ui_Container3 = NULL;
lv_obj_t *ui_Indicator = NULL;
void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 1024);
lv_obj_set_height( ui_Panel1, 328);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, 6 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Panel1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 944);
lv_obj_set_height( ui_Container1, 50);
lv_obj_set_x( ui_Container1, -288 );
lv_obj_set_y( ui_Container1, -130 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Container4 = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 150);
lv_obj_set_height( ui_Container4, 50);
lv_obj_set_x( ui_Container4, -288 );
lv_obj_set_y( ui_Container4, -130 );
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Indicator = lv_obj_create(ui_Container4);
lv_obj_set_size(ui_Indicator, 16, 15);
lv_obj_set_style_radius(ui_Indicator, LV_RADIUS_CIRCLE, 0);
lv_obj_set_style_bg_color(ui_Indicator, lv_palette_main(LV_PALETTE_RED), 0);
lv_obj_set_style_bg_opa(ui_Indicator, LV_OPA_COVER, 0);
lv_obj_set_align(ui_Indicator, LV_ALIGN_CENTER );

ui_Label1 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"--.-V");
lv_obj_set_style_text_font(ui_Label1, &ui_font_bitcount_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Container1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"---.- C");
lv_obj_set_style_text_font(ui_Label2, &ui_font_bitcount_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Panel1);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 971);
lv_obj_set_height( ui_Container2, 215);
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_Container3 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width(ui_Container3, 323);
lv_obj_set_height(ui_Container3, 240);
lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Panel1= NULL;
ui_Container1= NULL;
ui_Label1= NULL;
ui_Label2= NULL;
ui_Container2= NULL;
ui_Chart1= NULL;
ui_Container3= NULL;
ui_Indicator= NULL;

}
